//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GumpCompiler {
    using System.Linq;
    using System;
    
    
    public partial class DerivedEntityT4 : DerivedEntityT4Base {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 3 "DerivedEntityT4.tt"
 
var gump = this.Session["gump"] as gump;
var path = this.Session["path"] as string; 
var entity = this.Session["entity"] as Entity; 
var uniques_by_kind = entity.UniqueEntitiesByKind(gump);
var multiples = entity.MultipleEntities(gump);

            
            #line default
            #line hidden
            
            #line 10 "DerivedEntityT4.tt"
            this.Write("// ------------------------------------------------------------------------------" +
                    "\n//  <autogenerated>\n//      This code was generated by tool ");
            
            #line default
            #line hidden
            
            #line 12 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( GumpCompiler.Version.Name ));
            
            #line default
            #line hidden
            
            #line 12 "DerivedEntityT4.tt"
            this.Write(" v");
            
            #line default
            #line hidden
            
            #line 12 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( GumpCompiler.Version.Number ));
            
            #line default
            #line hidden
            
            #line 12 "DerivedEntityT4.tt"
            this.Write(".\n//      Changes to this file may cause incorrect behavior and will be lost if \n" +
                    "//      the code is regenerated.\n//  </autogenerated>\n// -----------------------" +
                    "-------------------------------------------------------\n#ifndef ");
            
            #line default
            #line hidden
            
            #line 17 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( gump.model.@namespace.ToUpper()  ));
            
            #line default
            #line hidden
            
            #line 17 "DerivedEntityT4.tt"
            this.Write("_GENERATED_BY_GUMP_");
            
            #line default
            #line hidden
            
            #line 17 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name.ToUpper() ));
            
            #line default
            #line hidden
            
            #line 17 "DerivedEntityT4.tt"
            this.Write("_H\n#define ");
            
            #line default
            #line hidden
            
            #line 18 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( gump.model.@namespace.ToUpper()  ));
            
            #line default
            #line hidden
            
            #line 18 "DerivedEntityT4.tt"
            this.Write("_GENERATED_BY_GUMP_");
            
            #line default
            #line hidden
            
            #line 18 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name.ToUpper() ));
            
            #line default
            #line hidden
            
            #line 18 "DerivedEntityT4.tt"
            this.Write("_H\n\n#include \"");
            
            #line default
            #line hidden
            
            #line 20 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( path ));
            
            #line default
            #line hidden
            
            #line 20 "DerivedEntityT4.tt"
            this.Write("/Entities/");
            
            #line default
            #line hidden
            
            #line 20 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.@base ));
            
            #line default
            #line hidden
            
            #line 20 "DerivedEntityT4.tt"
            this.Write(".h\"\n");
            
            #line default
            #line hidden
            
            #line 21 "DerivedEntityT4.tt"

foreach(var e in entity.AllEntities(gump)) { 

            
            #line default
            #line hidden
            
            #line 24 "DerivedEntityT4.tt"
            this.Write("#include \"");
            
            #line default
            #line hidden
            
            #line 24 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( path ));
            
            #line default
            #line hidden
            
            #line 24 "DerivedEntityT4.tt"
            this.Write("/Entities/");
            
            #line default
            #line hidden
            
            #line 24 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.name ));
            
            #line default
            #line hidden
            
            #line 24 "DerivedEntityT4.tt"
            this.Write(".h\"\n");
            
            #line default
            #line hidden
            
            #line 25 "DerivedEntityT4.tt"
  
  foreach(var ee in e.ChildEntities(gump)) { 

            
            #line default
            #line hidden
            
            #line 28 "DerivedEntityT4.tt"
            this.Write("#include \"");
            
            #line default
            #line hidden
            
            #line 28 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( path ));
            
            #line default
            #line hidden
            
            #line 28 "DerivedEntityT4.tt"
            this.Write("/Entities/");
            
            #line default
            #line hidden
            
            #line 28 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ee.name ));
            
            #line default
            #line hidden
            
            #line 28 "DerivedEntityT4.tt"
            this.Write(".h\"\n");
            
            #line default
            #line hidden
            
            #line 29 "DerivedEntityT4.tt"

  }
}

            
            #line default
            #line hidden
            
            #line 33 "DerivedEntityT4.tt"
            this.Write("\n#include \"");
            
            #line default
            #line hidden
            
            #line 34 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( path ));
            
            #line default
            #line hidden
            
            #line 34 "DerivedEntityT4.tt"
            this.Write("/Entities/EntityKind.h\"\n#include \"");
            
            #line default
            #line hidden
            
            #line 35 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( path ));
            
            #line default
            #line hidden
            
            #line 35 "DerivedEntityT4.tt"
            this.Write("/Entities/EntityTag.h\"\n\nnamespace ");
            
            #line default
            #line hidden
            
            #line 37 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( gump.model.@namespace ));
            
            #line default
            #line hidden
            
            #line 37 "DerivedEntityT4.tt"
            this.Write(" {\n\n  class ");
            
            #line default
            #line hidden
            
            #line 39 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 39 "DerivedEntityT4.tt"
            this.Write(" : public ");
            
            #line default
            #line hidden
            
            #line 39 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.@base ));
            
            #line default
            #line hidden
            
            #line 39 "DerivedEntityT4.tt"
            this.Write("\n  {\n  public:\n  \n    ");
            
            #line default
            #line hidden
            
            #line 43 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 43 "DerivedEntityT4.tt"
            this.Write("() {}\n\n    ");
            
            #line default
            #line hidden
            
            #line 45 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 45 "DerivedEntityT4.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 45 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 45 "DerivedEntityT4.tt"
            this.Write("&& e)\n      : ");
            
            #line default
            #line hidden
            
            #line 46 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.@base ));
            
            #line default
            #line hidden
            
            #line 46 "DerivedEntityT4.tt"
            this.Write("(e) {}\n    \n    ");
            
            #line default
            #line hidden
            
            #line 48 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 48 "DerivedEntityT4.tt"
            this.Write("(const ");
            
            #line default
            #line hidden
            
            #line 48 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 48 "DerivedEntityT4.tt"
            this.Write("& e)\n      : ");
            
            #line default
            #line hidden
            
            #line 49 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.@base ));
            
            #line default
            #line hidden
            
            #line 49 "DerivedEntityT4.tt"
            this.Write("(e) {}\n    \n    ");
            
            #line default
            #line hidden
            
            #line 51 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 51 "DerivedEntityT4.tt"
            this.Write("(const ");
            
            #line default
            #line hidden
            
            #line 51 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.@base ));
            
            #line default
            #line hidden
            
            #line 51 "DerivedEntityT4.tt"
            this.Write("& e)\n      : ");
            
            #line default
            #line hidden
            
            #line 52 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.@base ));
            
            #line default
            #line hidden
            
            #line 52 "DerivedEntityT4.tt"
            this.Write("(e) \n    {\n      ARCANE_ASSERT((e.tag() == ");
            
            #line default
            #line hidden
            
            #line 54 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Tag () ));
            
            #line default
            #line hidden
            
            #line 54 "DerivedEntityT4.tt"
            this.Write("), (\"entity tag error\"));\n    }\n   \n    ");
            
            #line default
            #line hidden
            
            #line 57 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 57 "DerivedEntityT4.tt"
            this.Write("(Gump::Private::Entity* e)\n      : ");
            
            #line default
            #line hidden
            
            #line 58 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.@base ));
            
            #line default
            #line hidden
            
            #line 58 "DerivedEntityT4.tt"
            this.Write("(e)\n    {\n      ARCANE_ASSERT((e->tag() == ");
            
            #line default
            #line hidden
            
            #line 60 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Tag () ));
            
            #line default
            #line hidden
            
            #line 60 "DerivedEntityT4.tt"
            this.Write("), (\"entity tag error\"));\n    }\n    \n    ");
            
            #line default
            #line hidden
            
            #line 63 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 63 "DerivedEntityT4.tt"
            this.Write("(const Gump::Entity& e)\n      : ");
            
            #line default
            #line hidden
            
            #line 64 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.@base ));
            
            #line default
            #line hidden
            
            #line 64 "DerivedEntityT4.tt"
            this.Write("(e)\n    {\n      ARCANE_ASSERT((e.tag() == ");
            
            #line default
            #line hidden
            
            #line 66 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Tag () ));
            
            #line default
            #line hidden
            
            #line 66 "DerivedEntityT4.tt"
            this.Write("), (\"entity tag error\"));\n    }  \n\n    ");
            
            #line default
            #line hidden
            
            #line 69 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 69 "DerivedEntityT4.tt"
            this.Write("& operator=(const ");
            
            #line default
            #line hidden
            
            #line 69 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 69 "DerivedEntityT4.tt"
            this.Write("& e)\n    {\n      m_private = e.m_private;\n      return *this;\n    }\n\n");
            
            #line default
            #line hidden
            
            #line 75 "DerivedEntityT4.tt"

foreach (var uniques in uniques_by_kind) {
  int i = 0;
  foreach (var e in uniques) {  

            
            #line default
            #line hidden
            
            #line 80 "DerivedEntityT4.tt"
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 80 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.name  ));
            
            #line default
            #line hidden
            
            #line 80 "DerivedEntityT4.tt"
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 80 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Object ()  ));
            
            #line default
            #line hidden
            
            #line 80 "DerivedEntityT4.tt"
            this.Write("() const {\n      return ");
            
            #line default
            #line hidden
            
            #line 81 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.name  ));
            
            #line default
            #line hidden
            
            #line 81 "DerivedEntityT4.tt"
            this.Write("(m_private->entity(");
            
            #line default
            #line hidden
            
            #line 81 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( i ));
            
            #line default
            #line hidden
            
            #line 81 "DerivedEntityT4.tt"
            this.Write(", ");
            
            #line default
            #line hidden
            
            #line 81 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Kind ()  ));
            
            #line default
            #line hidden
            
            #line 81 "DerivedEntityT4.tt"
            this.Write(")); \n    }\n\n");
            
            #line default
            #line hidden
            
            #line 84 "DerivedEntityT4.tt"
 
  }
}
foreach (var e in multiples.Where(ee => ee.@base == null)) {

            
            #line default
            #line hidden
            
            #line 89 "DerivedEntityT4.tt"
            this.Write("    Gump::EnumeratorT<");
            
            #line default
            #line hidden
            
            #line 89 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.name ));
            
            #line default
            #line hidden
            
            #line 89 "DerivedEntityT4.tt"
            this.Write("> ");
            
            #line default
            #line hidden
            
            #line 89 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Enumerator () ));
            
            #line default
            #line hidden
            
            #line 89 "DerivedEntityT4.tt"
            this.Write("() const { \n      return m_private->entities(");
            
            #line default
            #line hidden
            
            #line 90 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Kind () ));
            
            #line default
            #line hidden
            
            #line 90 "DerivedEntityT4.tt"
            this.Write("); \n    }\n    Arcane::Integer numberOf");
            
            #line default
            #line hidden
            
            #line 92 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Multiple () ));
            
            #line default
            #line hidden
            
            #line 92 "DerivedEntityT4.tt"
            this.Write("() const { \n      return m_private->numberOf(");
            
            #line default
            #line hidden
            
            #line 93 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Kind () ));
            
            #line default
            #line hidden
            
            #line 93 "DerivedEntityT4.tt"
            this.Write("); \n    }\n    ");
            
            #line default
            #line hidden
            
            #line 95 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.name ));
            
            #line default
            #line hidden
            
            #line 95 "DerivedEntityT4.tt"
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 95 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Object () ));
            
            #line default
            #line hidden
            
            #line 95 "DerivedEntityT4.tt"
            this.Write("(Arcane::Integer i) const { \n      return ");
            
            #line default
            #line hidden
            
            #line 96 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.name ));
            
            #line default
            #line hidden
            
            #line 96 "DerivedEntityT4.tt"
            this.Write("(m_private->entity(i, ");
            
            #line default
            #line hidden
            
            #line 96 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Kind () ));
            
            #line default
            #line hidden
            
            #line 96 "DerivedEntityT4.tt"
            this.Write(")); \n    }\n    ");
            
            #line default
            #line hidden
            
            #line 98 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.name ));
            
            #line default
            #line hidden
            
            #line 98 "DerivedEntityT4.tt"
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 98 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Object () ));
            
            #line default
            #line hidden
            
            #line 98 "DerivedEntityT4.tt"
            this.Write("(Arcane::String name) const { \n      return ");
            
            #line default
            #line hidden
            
            #line 99 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.name ));
            
            #line default
            #line hidden
            
            #line 99 "DerivedEntityT4.tt"
            this.Write("(m_private->entity(name, ");
            
            #line default
            #line hidden
            
            #line 99 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Kind () ));
            
            #line default
            #line hidden
            
            #line 99 "DerivedEntityT4.tt"
            this.Write(")); \n    }\n\n");
            
            #line default
            #line hidden
            
            #line 102 "DerivedEntityT4.tt"

}
foreach (var e in multiples.Where(ee => ee.@base != null)) {

            
            #line default
            #line hidden
            
            #line 106 "DerivedEntityT4.tt"
            this.Write("    Gump::EnumeratorT<");
            
            #line default
            #line hidden
            
            #line 106 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.name ));
            
            #line default
            #line hidden
            
            #line 106 "DerivedEntityT4.tt"
            this.Write("> ");
            
            #line default
            #line hidden
            
            #line 106 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Enumerator () ));
            
            #line default
            #line hidden
            
            #line 106 "DerivedEntityT4.tt"
            this.Write("() const { \n      return m_private->entities(");
            
            #line default
            #line hidden
            
            #line 107 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Kind () ));
            
            #line default
            #line hidden
            
            #line 107 "DerivedEntityT4.tt"
            this.Write(", ");
            
            #line default
            #line hidden
            
            #line 107 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Tag () ));
            
            #line default
            #line hidden
            
            #line 107 "DerivedEntityT4.tt"
            this.Write("); \n    }\n    Arcane::Integer numberOf");
            
            #line default
            #line hidden
            
            #line 109 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Multiple () ));
            
            #line default
            #line hidden
            
            #line 109 "DerivedEntityT4.tt"
            this.Write("() const { \n      return m_private->numberOf(");
            
            #line default
            #line hidden
            
            #line 110 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Kind () ));
            
            #line default
            #line hidden
            
            #line 110 "DerivedEntityT4.tt"
            this.Write(", ");
            
            #line default
            #line hidden
            
            #line 110 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.Tag () ));
            
            #line default
            #line hidden
            
            #line 110 "DerivedEntityT4.tt"
            this.Write("); \n    }\n    \n");
            
            #line default
            #line hidden
            
            #line 113 "DerivedEntityT4.tt"

}

            
            #line default
            #line hidden
            
            #line 116 "DerivedEntityT4.tt"
            this.Write("  };\n\n}\n\n#define ENUMERATE_");
            
            #line default
            #line hidden
            
            #line 120 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name.ToUpper() ));
            
            #line default
            #line hidden
            
            #line 120 "DerivedEntityT4.tt"
            this.Write("(e,enumerator) \\\n  for(auto e = enumerator; e.hasNext(); ++e)\n\n#define ENUMERATE_" +
                    "SOME_");
            
            #line default
            #line hidden
            
            #line 123 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name.ToUpper() ));
            
            #line default
            #line hidden
            
            #line 123 "DerivedEntityT4.tt"
            this.Write("(e,enumerator,predicat) \\\n  for(auto e = enumerator; e.hasNext(); ++e) if(not pre" +
                    "dicat) continue; else \n \n#endif /* ");
            
            #line default
            #line hidden
            
            #line 126 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( gump.model.@namespace.ToUpper()  ));
            
            #line default
            #line hidden
            
            #line 126 "DerivedEntityT4.tt"
            this.Write("_GENERATED_BY_GUMP_");
            
            #line default
            #line hidden
            
            #line 126 "DerivedEntityT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name.ToUpper() ));
            
            #line default
            #line hidden
            
            #line 126 "DerivedEntityT4.tt"
            this.Write("_H */\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class DerivedEntityT4Base {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
