//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GumpCompiler {
    using System.Linq;
    using System;
    
    
    public partial class Factory : FactoryBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 3 "Factory.tt"
 
var gump = this.Session["gump"] as gump;
//var path = this.Session["path"] as string; 

            
            #line default
            #line hidden
            
            #line 7 "Factory.tt"
            this.Write("// ------------------------------------------------------------------------------" +
                    "\n//  <autogenerated>\n//      This code was generated by tool ");
            
            #line default
            #line hidden
            
            #line 9 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( GumpCompiler.Version.Name ));
            
            #line default
            #line hidden
            
            #line 9 "Factory.tt"
            this.Write(" v");
            
            #line default
            #line hidden
            
            #line 9 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( GumpCompiler.Version.Number ));
            
            #line default
            #line hidden
            
            #line 9 "Factory.tt"
            this.Write(".\n//      Changes to this file may cause incorrect behavior and will be lost if \n" +
                    "//      the code is regenerated.\n//  </autogenerated>\n// -----------------------" +
                    "-------------------------------------------------------\n#ifndef ");
            
            #line default
            #line hidden
            
            #line 14 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( gump.model.@namespace.ToUpper()  ));
            
            #line default
            #line hidden
            
            #line 14 "Factory.tt"
            this.Write("_GENERATED_BY_GUMP_FACTORY_H\n#define ");
            
            #line default
            #line hidden
            
            #line 15 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( gump.model.@namespace.ToUpper()  ));
            
            #line default
            #line hidden
            
            #line 15 "Factory.tt"
            this.Write("_GENERATED_BY_GUMP_FACTORY_H\n\n#include \"ArcGeoSim/Gump/Factory.h\"\n\n");
            
            #line default
            #line hidden
            
            #line 19 "Factory.tt"
  
foreach(var entity in gump.Entities()) {

            
            #line default
            #line hidden
            
            #line 22 "Factory.tt"
            this.Write("#include \"");
            
            #line default
            #line hidden
            
            #line 22 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 22 "Factory.tt"
            this.Write("Builder.h\"\n");
            
            #line default
            #line hidden
            
            #line 23 "Factory.tt"
  
} 

            
            #line default
            #line hidden
            
            #line 26 "Factory.tt"
            this.Write("\nnamespace ");
            
            #line default
            #line hidden
            
            #line 27 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( gump.model.@namespace ));
            
            #line default
            #line hidden
            
            #line 27 "Factory.tt"
            this.Write(" {\n\n  class Factory : public Gump::Factory\n  {\n  public:\n\n    Factory()\n      : G" +
                    "ump::Factory(EK_NbEntities, ET_NbEntityTags, PK_NbProperties) {}\n\n");
            
            #line default
            #line hidden
            
            #line 36 "Factory.tt"
  
foreach(var entity in gump.Entities()) {
  var unique = entity.UniqueEntities(gump);
  if (unique.Count () == 0) { 

            
            #line default
            #line hidden
            
            #line 41 "Factory.tt"
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 41 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 41 "Factory.tt"
            this.Write("Builder new");
            
            #line default
            #line hidden
            
            #line 41 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 41 "Factory.tt"
            this.Write("(Arcane::String name)\n    {\n      return create(name, ");
            
            #line default
            #line hidden
            
            #line 43 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Kind () ));
            
            #line default
            #line hidden
            
            #line 43 "Factory.tt"
            this.Write(", ");
            
            #line default
            #line hidden
            
            #line 43 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Tag () ));
            
            #line default
            #line hidden
            
            #line 43 "Factory.tt"
            this.Write(");\n    }\n\n");
            
            #line default
            #line hidden
            
            #line 46 "Factory.tt"
   
  } else { 

            
            #line default
            #line hidden
            
            #line 49 "Factory.tt"
            this.Write("    ");
            
            #line default
            #line hidden
            
            #line 49 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 49 "Factory.tt"
            this.Write("Builder new");
            
            #line default
            #line hidden
            
            #line 49 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.name ));
            
            #line default
            #line hidden
            
            #line 49 "Factory.tt"
            this.Write("(Arcane::String name,\n");
            
            #line default
            #line hidden
            
            #line 50 "Factory.tt"
 
    int i = 0;
    foreach(var e in unique) { 

            
            #line default
            #line hidden
            
            #line 54 "Factory.tt"
            this.Write("            const ");
            
            #line default
            #line hidden
            
            #line 54 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( e.name ));
            
            #line default
            #line hidden
            
            #line 54 "Factory.tt"
            this.Write("Builder& builder_");
            
            #line default
            #line hidden
            
            #line 54 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( i++ ));
            
            #line default
            #line hidden
            
            #line 54 "Factory.tt"
 if (e != unique.Last ()) 
            
            #line default
            #line hidden
            
            #line 55 "Factory.tt"
            this.Write(",\n");
            
            #line default
            #line hidden
            
            #line 56 "Factory.tt"
 else 
            
            #line default
            #line hidden
            
            #line 57 "Factory.tt"
            this.Write(") \n");
            
            #line default
            #line hidden
            
            #line 58 "Factory.tt"

    } 

            
            #line default
            #line hidden
            
            #line 61 "Factory.tt"
            this.Write("    {\n      Gump::Builder builder = create(name, ");
            
            #line default
            #line hidden
            
            #line 62 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Kind () ));
            
            #line default
            #line hidden
            
            #line 62 "Factory.tt"
            this.Write(", ");
            
            #line default
            #line hidden
            
            #line 62 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Tag () ));
            
            #line default
            #line hidden
            
            #line 62 "Factory.tt"
            this.Write(");\n");
            
            #line default
            #line hidden
            
            #line 63 "Factory.tt"

    i = 0; 
    foreach(var e in unique) { 

            
            #line default
            #line hidden
            
            #line 67 "Factory.tt"
            this.Write("      builder.push(builder_");
            
            #line default
            #line hidden
            
            #line 67 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( i++ ));
            
            #line default
            #line hidden
            
            #line 67 "Factory.tt"
            this.Write(");\n");
            
            #line default
            #line hidden
            
            #line 68 "Factory.tt"
      
    } 

            
            #line default
            #line hidden
            
            #line 71 "Factory.tt"
            this.Write("      return builder;\n    }\n\n");
            
            #line default
            #line hidden
            
            #line 74 "Factory.tt"

  }
} 

            
            #line default
            #line hidden
            
            #line 78 "Factory.tt"
            this.Write("  };\n\n}\n#endif /* ");
            
            #line default
            #line hidden
            
            #line 81 "Factory.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( gump.model.@namespace.ToUpper()  ));
            
            #line default
            #line hidden
            
            #line 81 "Factory.tt"
            this.Write("_GENERATED_BY_GUMP_FACTORY_H */\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class FactoryBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
