//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GumpCompiler {
    using System;
    
    
    public partial class PropertyTraitsT4 : PropertyTraitsT4Base {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 2 "PropertyTraitsT4.tt"
 
var gump = this.Session["gump"] as gump; 
var path = this.Session["path"] as string; 
var properties = gump.Properties ();

            
            #line default
            #line hidden
            
            #line 7 "PropertyTraitsT4.tt"
            this.Write("// ------------------------------------------------------------------------------" +
                    "\n//  <autogenerated>\n//      This code was generated by tool ");
            
            #line default
            #line hidden
            
            #line 9 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( GumpCompiler.Version.Name ));
            
            #line default
            #line hidden
            
            #line 9 "PropertyTraitsT4.tt"
            this.Write(" v");
            
            #line default
            #line hidden
            
            #line 9 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( GumpCompiler.Version.Number ));
            
            #line default
            #line hidden
            
            #line 9 "PropertyTraitsT4.tt"
            this.Write(".\n//      Changes to this file may cause incorrect behavior and will be lost if \n" +
                    "//      the code is regenerated.\n//  </autogenerated>\n// -----------------------" +
                    "-------------------------------------------------------\n#ifndef ");
            
            #line default
            #line hidden
            
            #line 14 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( gump.model.@namespace.ToUpper() ));
            
            #line default
            #line hidden
            
            #line 14 "PropertyTraitsT4.tt"
            this.Write("_GENERATED_BY_GUMP_PROPERTYTRAITS_H\n#define ");
            
            #line default
            #line hidden
            
            #line 15 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( gump.model.@namespace.ToUpper() ));
            
            #line default
            #line hidden
            
            #line 15 "PropertyTraitsT4.tt"
            this.Write("_GENERATED_BY_GUMP_PROPERTYTRAITS_H\n\n#include \"ArcGeoSim/Physics/Gump/IConverter." +
                    "h\"\n\n#include \"");
            
            #line default
            #line hidden
            
            #line 19 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( path ));
            
            #line default
            #line hidden
            
            #line 19 "PropertyTraitsT4.tt"
            this.Write("/Properties.h\"\n#include \"");
            
            #line default
            #line hidden
            
            #line 20 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( path ));
            
            #line default
            #line hidden
            
            #line 20 "PropertyTraitsT4.tt"
            this.Write("/Properties/PropertyKind.h\"\n\n#include <arcane/utils/FatalErrorException.h>\n\nnames" +
                    "pace ");
            
            #line default
            #line hidden
            
            #line 24 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( gump.model.@namespace ));
            
            #line default
            #line hidden
            
            #line 24 "PropertyTraitsT4.tt"
            this.Write(" {\n\n  template<ePropertyKind> struct PropertyTraits;\n  \n");
            
            #line default
            #line hidden
            
            #line 28 "PropertyTraitsT4.tt"
  
foreach(var property in properties) {

            
            #line default
            #line hidden
            
            #line 31 "PropertyTraitsT4.tt"
            this.Write("  template<> struct PropertyTraits<");
            
            #line default
            #line hidden
            
            #line 31 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( property.Kind () ));
            
            #line default
            #line hidden
            
            #line 31 "PropertyTraitsT4.tt"
            this.Write(">\n  { \n    typedef ");
            
            #line default
            #line hidden
            
            #line 33 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( property.name ));
            
            #line default
            #line hidden
            
            #line 33 "PropertyTraitsT4.tt"
            this.Write(" type;\n    \n    Arcane::String toString() const { return \"");
            
            #line default
            #line hidden
            
            #line 35 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( property.name ));
            
            #line default
            #line hidden
            
            #line 35 "PropertyTraitsT4.tt"
            this.Write("\"; }\n  };\n  \n");
            
            #line default
            #line hidden
            
            #line 38 "PropertyTraitsT4.tt"
  }
            
            #line default
            #line hidden
            
            #line 39 "PropertyTraitsT4.tt"
            this.Write(@"
  struct PropertyKindConverter
    : public Gump::IConverter
  {
    virtual ~PropertyKindConverter() {}
  
    Arcane::Integer undefined() const 
    { 
      return PK_UndefinedProperty; 
    }
  
    Arcane::Integer convert(Arcane::String s) const 
    { 
      return operator()(s); 
    }
    
    Arcane::String operator()(ePropertyKind k) const
    {
      switch(k)
      {
");
            
            #line default
            #line hidden
            
            #line 59 "PropertyTraitsT4.tt"
  
foreach(var property in properties) {

            
            #line default
            #line hidden
            
            #line 62 "PropertyTraitsT4.tt"
            this.Write("        case ");
            
            #line default
            #line hidden
            
            #line 62 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( property.Kind () ));
            
            #line default
            #line hidden
            
            #line 62 "PropertyTraitsT4.tt"
            this.Write(": return \"");
            
            #line default
            #line hidden
            
            #line 62 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( property.name ));
            
            #line default
            #line hidden
            
            #line 62 "PropertyTraitsT4.tt"
            this.Write("\";\n");
            
            #line default
            #line hidden
            
            #line 63 "PropertyTraitsT4.tt"
 
}

            
            #line default
            #line hidden
            
            #line 66 "PropertyTraitsT4.tt"
            this.Write("      default:\n          throw Arcane::FatalErrorException(\"Property kind cast to" +
                    " string, error!\");\n      }\n    }\n      \n    ePropertyKind operator()(Arcane::Str" +
                    "ing s) const\n    { \n");
            
            #line default
            #line hidden
            
            #line 73 "PropertyTraitsT4.tt"
  
foreach(var property in properties) {

            
            #line default
            #line hidden
            
            #line 76 "PropertyTraitsT4.tt"
            this.Write("      if(s == \"");
            
            #line default
            #line hidden
            
            #line 76 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( property.name ));
            
            #line default
            #line hidden
            
            #line 76 "PropertyTraitsT4.tt"
            this.Write("\") return ");
            
            #line default
            #line hidden
            
            #line 76 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( property.Kind () ));
            
            #line default
            #line hidden
            
            #line 76 "PropertyTraitsT4.tt"
            this.Write(";\n");
            
            #line default
            #line hidden
            
            #line 77 "PropertyTraitsT4.tt"

}

            
            #line default
            #line hidden
            
            #line 80 "PropertyTraitsT4.tt"
            this.Write(" \n      return PK_UndefinedProperty;\n    }\n  };\n\n}\n\n#endif /* ");
            
            #line default
            #line hidden
            
            #line 87 "PropertyTraitsT4.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( gump.model.@namespace.ToUpper() ));
            
            #line default
            #line hidden
            
            #line 87 "PropertyTraitsT4.tt"
            this.Write("_GENERATED_BY_GUMP_PROPERTYTRAITS_H */\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class PropertyTraitsT4Base {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
