//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace CMakeListGenerator {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("makefile", Namespace="", IsNullable=false)]
    public partial class Makefile {
        
        private Package[] neededpackagesField;
        
        private Files[] filesField;
        
        private Directory[] directoriesField;
        
        private string dependField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("needed-packages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("package", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Package[] neededpackages {
            get {
                return this.neededpackagesField;
            }
            set {
                this.neededpackagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Files[] files {
            get {
                return this.filesField;
            }
            set {
                this.filesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("directory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Directory[] directories {
            get {
                return this.directoriesField;
            }
            set {
                this.directoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string depend {
            get {
                return this.dependField;
            }
            set {
                this.dependField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Package {
        
        private string nameField;
        
        private bool optionalField;
        
        private bool optionalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool optional {
            get {
                return this.optionalField;
            }
            set {
                this.optionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optionalSpecified {
            get {
                return this.optionalFieldSpecified;
            }
            set {
                this.optionalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ifpen.fr/ArcGeoSim")]
    public partial class Directory {
        
        private string dependField;
        
        private bool recursiveField;
        
        private bool recursiveFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string depend {
            get {
                return this.dependField;
            }
            set {
                this.dependField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool recursive {
            get {
                return this.recursiveField;
            }
            set {
                this.recursiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recursiveSpecified {
            get {
                return this.recursiveFieldSpecified;
            }
            set {
                this.recursiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class File {
        
        private bool headerField;
        
        private bool headerFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool headerSpecified {
            get {
                return this.headerFieldSpecified;
            }
            set {
                this.headerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Files {
        
        private File[] fileField;
        
        private Language languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("file", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public File[] file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Language language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum Language {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("c++")]
        c,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("c++header")]
        cheader,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("c")]
        c1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("cheader")]
        cheader1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("c#")]
        c2,
        
        /// <remarks/>
        module,
        
        /// <remarks/>
        service,
        
        /// <remarks/>
        f90,
        
        /// <remarks/>
        axl,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("axl[strong]")]
        axlstrong,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("axl[case+strong]")]
        axlcasestrong,
        
        /// <remarks/>
        law,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("law[debug]")]
        lawdebug,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("law[sequential]")]
        lawsequential,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("law[inference=onnx]")]
        lawinferenceonnx,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("service[strong]")]
        servicestrong,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("service[case+strong]")]
        servicecasestrong,
        
        /// <remarks/>
        gump,
    }
}
